### ISSUE TITLE
webthings 1.0 addon installer points to old version of candle manager

### ISSUE THREAD

**Issue by maarten-k** [createcandle/Candle-manager-addon#26]
When trying to installing the candle manager addon in webthings the  [addon repository points](https://api.webthings.io:8443/addons?arch=linux-arm&version=1.0.0&node=64&python=2.7%2C3.7) to an  [unavaible and old release](https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/Candle-manager-addon-1.1.0-linux-arm-v3.7.tgz )

I updated mozilla webthings to webthings.io  so the culprit might be there.

**Comment by createcandle** [comment]
Yes, this problem was noted and should be fixed now.

**Comment by maarten-k** [comment]
Thanks for the update. I removed the manual installed version and installed the current version: it installed without problems.
