### ISSUE TITLE
Candle Manager Page fails to load

### ISSUE THREAD

**Issue by cullenskyward** [createcandle/Candle-manager-addon#28]
For some reason when I try to access the candle manager page it gives me a ERR_NAME_NOT_RESOLVED error after it says "Sending request info to gateway.local" And when I change the default name in settings for the gateway it still says its sending request info to GATEWAY.local not the name I set it to, also this has been happening with anything that ends with ".local", it always fails to load the page, Ex: The musicbox program will want me to go to musicbox.local and it will give the same error.

**Comment by createcandle** [comment]
I'm not sure I follow. Where do you see this? In your browser's javascript console? In the internal logs?

I can't find `Sending request info to` in any of the Candle Manager code.

- Are you sure it says the correct `something.local` in the url bar of your browser?
- Have you tried refreshing the page and/or rebooting?
- If you enable debugging for the addon, do you see any errors show up in the internal log?
- Do you see any errors in your browser's javascript console? (right mouse button -> inspect)

The code does use `gateway.local` as the fallback option if it is unable to figure out the IP address of the server (if 'socket' fails, for instance).

Are you running the WebThings Gateway Raspberry Pi image, or something else?

**Comment by createcandle** [comment]
I believe I've found the issue. Thank you for bringing this to my attention!
