### ISSUE TITLE
Candle Manager cannot be loaded due to https mixed content restriction 

### ISSUE THREAD

**Issue by wanjatschuor** [createcandle/Candle-manager-addon#9]
Type: Bug
WebThings Gatewaz Version: 0.10.0 (on Raspberry Pi 3)
Candle Manager Version:        1.0.4

The WebThings Interface is transportet via https, the candle manager on port 8686 is loaded via http. In Chrome this is not possible and leads to a disfunctional User interface.

Error output from console:

`Mixed Content: The page at 'https://xxxxxxx.mozilla-iot.org/things' was loaded over HTTPS, but requested an insecure resource 'http://xxxxxx.mozilla-iot.org:8686/'. This request has been blocked; the content must be served over HTTPS.`

The behavior is observed when trying to reach the local ip address, the dns (gateway.local) and the registered sub-domain (x-ed out in the log).

Entering http://subdomain.mozilla-iot.org:8686 to adressbar manually works and starts the Candle Manager. Adding devices this way is possible.

**Comment by createcandle** [comment]
Thanks! This should be fixed now.
